name: Hassfest

on:
  push:
  pull_request:

jobs:
  hassfest:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master
